/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HelloWorld_CONSTANTS_H
#define HelloWorld_CONSTANTS_H

#include "HelloWorld_types.h"



class HelloWorldConstants {
 public:
  HelloWorldConstants();

};

extern const HelloWorldConstants g_HelloWorld_constants;



#endif
