/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "HelloWorld_constants.h"



const HelloWorldConstants g_HelloWorld_constants;

HelloWorldConstants::HelloWorldConstants() {
}



